# Generated by Django 3.1.1 on 2020-09-04 05:22
# flake8: noqa
from django.db import migrations, models
import django_backblaze_b2.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                (
                    "publicFile",
                    models.FileField(
                        storage=django_backblaze_b2.storages.PublicStorage(),
                        upload_to="uploads",
                        verbose_name="Public File",
                    ),
                ),
                (
                    "loggedInFile",
                    models.FileField(
                        storage=django_backblaze_b2.storages.LoggedInStorage(),
                        upload_to="uploads",
                        verbose_name="Logged-In File",
                    ),
                ),
                (
                    "adminFile",
                    models.FileField(
                        storage=django_backblaze_b2.storages.AdminStorage(),
                        upload_to="uploads",
                        verbose_name="Admin-Only File",
                    ),
                ),
            ],
        ),
    ]
